# Generated by Django 5.2.8 on 2025-11-25 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('my_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('item_id', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('status', models.CharField(choices=[('UNANSWERED', 'Sin responder'), ('ANSWERED', 'Respondida'), ('CLOSED_UNANSWERED', 'Cerrada sin responder'), ('UNDER_REVIEW', 'En revisión'), ('BANNED', 'Bloqueada')], max_length=20)),
                ('date_created', models.DateTimeField()),
                ('from_user_id', models.BigIntegerField()),
                ('answer_text', models.TextField(blank=True, null=True)),
                ('answer_date_created', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meli_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='my_auth.meliuser')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
    ]
