# Generated by Django 5.2.8 on 2026-01-09 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('my_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('question', 'Nueva pregunta'), ('order', 'Actualización de orden')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('question_id', models.BigIntegerField(blank=True, null=True)),
                ('order_id', models.BigIntegerField(blank=True, null=True)),
                ('status_change', models.CharField(blank=True, max_length=50, null=True)),
                ('meli_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='my_auth.meliuser')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['meli_user', '-created_at'], name='notificatio_meli_us_662c4c_idx'), models.Index(fields=['type'], name='notificatio_type_ea918f_idx')],
            },
        ),
    ]
